### ISSUE TITLE
Error when interacting with a KL125

### ISSUE THREAD

**Issue by afastaudir8** [turnupthebassto11/kasify#1]
I'm receiving this traceback when running the script. It works for about 1 second then does this 
```Currently playing Pink Floyd - Let There Be More Light - 5xUz3xvyPPrNfnBrh9IOZa
Traceback (most recent call last):
  File "/home/afastaudir8/.local/lib/python3.10/site-packages/kasa/protocol.py", line 112, in close
    await writer.wait_closed()
  File "/usr/lib/python3.10/asyncio/streams.py", line 344, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/afastaudir8/Documents/kasify/./kasify.py", line 94, in <module>
    loop()
  File "/home/afastaudir8/Documents/kasify/./kasify.py", line 91, in loop
    get_beats(beat_list, t_id, start_time, song_length, offset)
  File "/home/afastaudir8/Documents/kasify/./kasify.py", line 83, in get_beats
    asyncio.run(color(rhue))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/afastaudir8/Documents/kasify/./kasify.py", line 44, in color
    await bulb.update()
  File "/home/afastaudir8/.local/lib/python3.10/site-packages/kasa/smartdevice.py", line 314, in update
    self._last_update = await self.protocol.query(req)
  File "/home/afastaudir8/.local/lib/python3.10/site-packages/kasa/protocol.py", line 73, in query
    return await self._query(request, retry_count, timeout)
  File "/home/afastaudir8/.local/lib/python3.10/site-packages/kasa/protocol.py", line 163, in _query
    raise SmartDeviceException(
kasa.exceptions.SmartDeviceException: Unable to query the device 192.168.2.174: [Errno 104] Connection reset by peer
```

**Comment by turnupthebassto11** [comment]
Connection reset by peer sounds like an issue connecting to your bulb

**Comment by afastaudir8** [comment]
It looks like it's losing connection after a bit. The device shows up fine when running kasa-python. I'll try it on a different wifi network

**Comment by afastaudir8** [comment]
Weird. It's having the same issue on the other network. Did you ever have a similar issue?

**Comment by turnupthebassto11** [comment]
The only connection issues I had was after an extended period of time some
of the requests would timeout possibly due tue how fast they were coming in
but the bulb would still continue to keep time and change color. I also
have a KL130 not sure if that makes a difference.

**Comment by afastaudir8** [comment]
I don't think the model should make a difference. I should try with a slower song. Maybe the requests could be coming in too fast?

**Comment by afastaudir8** [comment]
I just did a very quick and dirty workaround where it just retries after a connection reset which sorta did the trick. I’ll make a PR.
